### PR TITLE
Fix handling of allOf when generating models

### LINKED ISSUE #14: Model generator does resolve 'allOf' schema references correctly
This works:

```
"Pet": {
            "allOf": [
                {
                    "$ref": "NewPet"
                },
                {
                    "required": [
                        "id"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                }
            ]
        }
```

but if you use the standard '#/definitions/NewPet' rather than 'NewPet'

```
"Pet": {
            "allOf": [
                {
                    "$ref": "#/definitions/NewPet"
                },
                {
                    "required": [
                        "id"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                }
            ]
        }
```

then the model(s) are incorrectly generated.

### PR DESCRIPTION
**Pull request by mastersingh24**
A follow-up for #15, fixes #14

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @mastersingh24, thank you for the new patch. The code looks good! Could you please fix the commit message to follow the [50/72 rule](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)? If you are not familiar with git history rewriting, the commands are `git commit --amend` and then `git push -f`.

**Comment by mastersingh24** [comment]
Just checking in.  Anything else needed from me?

**Comment by 0candy** [comment]
@bajtos Is this code ready to be merged?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
The build on Windows failed in the cleanup step because of a "file or path name too long" error, see http://ci.strongloop.com/job/loopback-swagger/node=5.x,os=windows/366/console

```
[ddb389d7] $ cmd.exe /C '"rm -rf %BUILD_FRAMEWORK_ROOT% && exit %%ERRORLEVEL%%"'
rm: cannot remove `D:\\t\\t4301112590479895201dirbfr/node_modules/build-framework/node_modules/istanbul/node_modules/handlebars/node_modules/uglify-js/node_modules/yargs/node_modules/cliui/node_modules/center-align/node_modules/align-text/node_modules/kind-of/node_modules/is-buffer': File or path name too long
```

Strangely enough, the master branch seems to be passing. @rmg could you PTAL?

**Comment by bajtos** [comment]
Landed, thank you @mastersingh24 for your contribution!

**Comment by rmg** [comment]
@bajtos that was a mistake on my part. I upgraded build-framework but forgot to do package it with npm-3 so that its dependency tree didn't go to deep. It is fixed now.

**Comment by bajtos** [comment]
> @rmg  that was a mistake on my part. I upgraded build-framework but forgot to do package it with npm-3 so that its dependency tree didn't go to deep. It is fixed now.

Thank you!

**Pull request merged**
