### PR TITLE
Change format of Date to Date-Time 

### PR DESCRIPTION
**Pull request by B-Stefan**
According to #35 I changed the date format to date-time instead of date

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by richardpringle** [comment]
ok to test

**Comment by bajtos** [comment]
@B-Stefan hello, thank you for the pull request, the proposed change makes a lot of sense to me.

My main concern is whether this is a breaking change that should be released as a new major version, or whether we can consider it as a bug fix.

@raymondfeng @ritch @superkhau @STRML thoughts?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by STRML** [comment]
This seems like a bugfix to me @bajtos, no need for a major IMO

**Comment by superkhau** [comment]
I agree with @STRML that this is a bugfix since this change follows the swagger 2.0 spec. I can see your point @bajtos regarding the next major though because whoever is using "date" will get different behaviour with this change. Feature flag seems like a safer medium -- use old behav or follow 2.0 spec by setting some flag on/off.

**Comment by bajtos** [comment]
Thank you for the comments. Considering that strong-remoting is already accepting and producing values in `date-time` format, and this the current Swagger description is in fact describing the API incorrectly, I'll treat this change as a bug-fix.

**Comment by bajtos** [comment]
Hi @B-Stefan, your patch does not pass `npm test` and the commit message does not follow our [50/72 rule](http://loopback.io/doc/en/contrib/git-commit-messages.html). To speed things up, I took this patch over and fixed the problems in #68

**Pull request closed without merging**
