### PR TITLE
specgen: Retrieve description from package.json

### PR DESCRIPTION
**Pull request by MelleB**
### Description
This patch retrieves a project description from package.json

#### Related issues
-connect to #122 

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Thank you @MelleB for the contribution. The changes look reasonably at high level, I'll try to find some time later this week to review them in more detail.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed, thank you @MelleB for your first contribution! ❤️

**Comment by MelleB** [comment]
Thanks a lot for the swift review and approval! :+1:

**Pull request merged**
