### PR TITLE
feat(route-helper): Add 'documented' flag for hiding params

### PR DESCRIPTION
**Pull request by STRML**
### Description

Adds a `documented` parameter to `'accepts'` - good for deprecating old parameters. `parameterDeprecated` is a thing in OpenAPI 3.0 (https://github.com/OAI/OpenAPI-Specification/pull/637/files) but not in 2.0, so this works well in the meantime and may have other uses even when we get to 3.0.

##### Example

```js
{
  accepts: [
    {arg: 'id', type: 'string'},
    {arg: 'undocumented', type: 'string', documented: false},
  ],
}
```

#### Related issues
None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by STRML** [comment]
It already is: 

https://github.com/strongloop/loopback-swagger/blob/db25c46297ab7ee3ac628c6064db2d87fc3ab1a3/lib/specgen/swagger-spec-generator.js#L82

**Comment by zbarbuto** [comment]
Ah, right you are... not sure why I thought it didn't exist - must have been thinking of something else 

https://github.com/strongloop/strong-remoting/blob/master/lib/rest-adapter.js#L570

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@STRML could you please update our documentation to mention this new flag too? Here is the page to update: [_includes/content/rm-options.md](https://github.com/strongloop/loopback.io/blob/29a145409505448cf9d6bf83948f782dccefc9b2/_includes/content/rm-options.md) and here are the instructions for contributing to our docs: http://loopback.io/doc/en/contrib/doc-contrib.html

**Comment by STRML** [comment]
https://github.com/strongloop/loopback.io/pull/500

**Comment by bajtos** [comment]
Awesome, thank you for the doc contribution too!

I have landed the patch and released it in `loopback-swagger@5.2.0`.

Enjoy 😄

**Pull request merged**
