### PR TITLE
Add support for schema reference objects for 'allOf'

### LINKED ISSUE #14: Model generator does resolve 'allOf' schema references correctly
This works:

```
"Pet": {
            "allOf": [
                {
                    "$ref": "NewPet"
                },
                {
                    "required": [
                        "id"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                }
            ]
        }
```

but if you use the standard '#/definitions/NewPet' rather than 'NewPet'

```
"Pet": {
            "allOf": [
                {
                    "$ref": "#/definitions/NewPet"
                },
                {
                    "required": [
                        "id"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                }
            ]
        }
```

then the model(s) are incorrectly generated.

### PR DESCRIPTION
**Pull request by mastersingh24**
Fixes #14

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @mastersingh24, thank you for the pull request.

Quoting from #14, I think the first example is an invalid usage and should not be supported:

```
"Pet": {
            "allOf": [
                {
                    "$ref": "NewPet"
                },
                {
                    "required": [
                        "id"
                    ],
                    "properties": {
                        "id": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                }
            ]
        }
```

Could you please simplify your patch?

**Comment by mastersingh24** [comment]
@bajtos  - not sure what you mean by "simplify"?  Do you just want to handle extracting the schema reference inline rather than having an extra function?  Or just cleanup the fact that I messed up with the commented code?  Or both?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by mastersingh24** [comment]
sorry - hit the wrong button

**Comment by bajtos** [comment]
@mastersingh24 From what I remember, one of your changes looked like a fix for a bug in our current implementation, that's the part which I would still like to land. Unfortunately the code is gone after a force-push, so I cannot provide more specific details :(

**Pull request closed without merging**
