### PR TITLE
support customer schema

### PR DESCRIPTION
**Pull request by sqlwwx**
Related: https://github.com/strongloop/loopback-swagger/pull/45

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@sqlwwx thank you for the pull request. Please explain in more details what are you trying to solve, you can edit the description field at the top.

Also please add a unit-test to demonstrate your feature in practice and to prevent regressions in the future.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by Biax2099** [comment]
Its possible to use custom schema e not just 

> **x-any, ObjectID, and GeoPoint**  ?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Closing this pull request as abandoned. Feel free to reopen if you have time to work on this again.

Also note that #45 has been already landed and released, thus this change may not be needed at the end.

**Pull request closed without merging**
